import type { AdapterKind, BootstrapStateJson, WorkspaceScanFacts } from '../types.js';
import { buildAndWriteUnderstandingArtifacts } from '../understanding/buildUnderstanding.js';
import { buildProjectStateFromScan } from './buildFromScan.js';
import { formatProjectSnapshotMarkdown } from './snapshot.js';
import { writeProjectBuiltState } from './store.js';

/** Unified scan path — MCP / CLI / IDE fallback share one state-builder implementation. */
export async function rebuildArtifactsFromScan(
  workspaceRoot: string,
  scan: WorkspaceScanFacts,
  state?: BootstrapStateJson,
  writer: AdapterKind = 'mcp',
): Promise<void> {
  const built = buildProjectStateFromScan(scan, state);
  let md = formatProjectSnapshotMarkdown(built);
  if (writer === 'cli' || writer === 'mcp') {
    md += `\n(generated by Contorium scan-driven bootstrap — ${writer} adapter; IDE events may refine this)\n`;
  }
  await writeProjectBuiltState(workspaceRoot, built, md);
  await buildAndWriteUnderstandingArtifacts({
    workspaceRoot,
    state,
    built,
    scan,
  }).catch(() => undefined);
}
